In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model 



In [3]:
df=pd.read_csv("F:\Codenera\DataScience\ML Scikit-Learn\\homepricess.csv")
df

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\hp\AppData\Local\Temp\ipykernel_14596\3253007295.py:1: SyntaxWarning: invalid escape sequence '\C'
  df=pd.read_csv("F:\Codenera\DataScience\ML Scikit-Learn\\homepricess.csv")


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
df.bedrooms=df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
reg=linear_model.LinearRegression()
reg.fit(df.drop("price",axis="columns"),df.price)

LinearRegression()

In [7]:
reg.predict([[3100,4,16]])

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([610564.60565965])

In [42]:
import pandas as pd

# Data
data = {
    "Horsepower": [130, 250, 190, 170, 200, 160, 220, 140, 210, 180],
    "Engine Size (L)": [2.5, 3.6, 3.0, 2.4, 3.2, 2.8, 3.5, 2.3, 3.3, 2.9],
    "Curb Weight (lbs)": [3200, 4000, 3600, 3300, 3700, 3400, 3900, 3100, 3800, 3500],
    "Highway MPG": [30, 24, 27, 28, 26, 29, 25, 31, 25, 28],
    "Price": [22000, 35000, 28000, 26000, 30000, 25000, 32000, 23000, 31000, 27000]
}

# Create DataFrame
df = pd.DataFrame(data)

# Save to CSV
df.to_csv('car_data.csv', index=False)

print("CSV file 'car_data.csv' created successfully!")


CSV file 'car_data.csv' created successfully!


In [43]:
df=pd.read_csv("F:\Codenera\DataScience\ML Scikit-Learn\\car_data.csv")
df

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\hp\AppData\Local\Temp\ipykernel_14596\1956907145.py:1: SyntaxWarning: invalid escape sequence '\C'
  df=pd.read_csv("F:\Codenera\DataScience\ML Scikit-Learn\\car_data.csv")


Horsepower  Engine Size (L)  Curb Weight (lbs)  Highway MPG  Price
0         130              2.5               3200           30  22000
1         250              3.6               4000           24  35000
2         190              3.0               3600           27  28000
3         170              2.4               3300           28  26000
4         200              3.2               3700           26  30000
5         160              2.8               3400           29  25000
6         220              3.5               3900           25  32000
7         140              2.3               3100           31  23000
8         210              3.3               3800           25  31000
9         180              2.9               3500           28  27000

In [44]:
reg.predict([[170,2.5,3150,28]])

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([30416.90140845])

In [45]:
reg.coef_

array([  125.35211268,  9295.77464789,   -23.32394366, -1070.42253521])

In [46]:
reg.intercept_

89309.85915494314